"""System prompt + forced tool schema for the bulk-import STRUCTURE extraction
call only (stem, alternatives, which is correct, domain, images).

Explanation content (comment/generalComment/topics/relatedServices) used to
be generated by this same call, but that produced noticeably weaker
explanations than the interactive "Generate with AI" flow — a completely
separate, much richer prompt. Both now go through the same AgentCore Runtime
review agent instead (see app.py's `_generate_explanation` call, made right
after this extraction succeeds) — this module only extracts structure.

Built per-invocation (not static) because the valid domain list depends on
the target pack — see build_system_prompt/build_tool_schema. Kept in its own
module so the prompt text can be iterated on without touching the Lambda's
control flow in app.py.
"""

BASE_SYSTEM_PROMPT = """You are extracting ONE structured multiple-choice certification exam question from raw, messy source material. The material is either page images from a browser-printed PDF quiz-results export, or scraped Markdown text (possibly with duplicated headings).

Rules:
- Extract exactly ONE question: its stem, its alternatives, and which one(s) are correct.
- The stem is EVERYTHING from the start of the question up to (but not including) the first answer option — copy it COMPLETE AND VERBATIM, including every scenario paragraph before the final question sentence. A real exam stem is very often 2-4 paragraphs (company/context, constraints, what's already been tried, THEN the question itself) — do not treat the earlier paragraphs as optional framing to drop or compress. Keeping only the last sentence/paragraph and discarding the scenario before it is a critical extraction failure, not an acceptable summary — the scenario details are frequently required to pick the correct answer.
- IGNORE any past-test-taker status labels near the question (e.g. "Incorreto", "Correto", "Ignorado", "Ignored", or a lone "Correct"/"Incorrect" placeholder line sitting next to an option with no other content) — these describe what some OTHER person answered before on this exam attempt, NOT the true correct answer.
- The true correct answer is identified ONLY by: (a) explicit prose such as "Hence, the correct answer is: ..." / "Correct option: ..." / "Resposta correta e explicação geral", or (b) a visually distinguished box/label such as "Resposta correta" / "Correct answer" with a different border color from the other options.
- If the question requires selecting more than one option (e.g. "Select TWO"), mark ALL of the truly correct alternatives with isCorrect: true.
- IGNORE any unrelated supplementary/tutorial/reference content that appears in the supplied material (e.g. a full page of an unrelated linked blog/doc article with its own diagrams) — extract ONLY the actual question and alternatives.
- IGNORE trailing "References:" / "Check out these Cheat Sheets:" link blocks.
- Write a short, descriptive title.
- Images — placement rule: place an image's `{{IMG:n}}` placeholder (n = 0-based index among the images you were given, in the order given) in the QUESTION STEM or in an ALTERNATIVE'S "text" field ONLY IF examining that image is MANDATORY to answer the question — meaning the stem itself explicitly depends on it (e.g. it says "as shown below", "based on the following diagram", "given the configuration above", "in the screenshot below") and the question cannot be correctly answered from the text alone. If an image is merely explanatory/illustrative — for example, it only supports the correct answer's rationale — do NOT place it in the stem or any alternative's "text"; omit it entirely (there is no explanation field in this extraction to place it in — the review agent that writes the explanation does not receive images, so an explanatory-only image is not carried forward). Never write literal `![...](...)` Markdown image syntax yourself — always use `{{IMG:n}}` for any image you place, even if the source text already contained its own image syntax at that spot. When in doubt whether the stem truly requires the image, prefer omitting it.

Examples of images that ARE mandatory in the stem (the question cannot be answered without them):
1. "A company has the VPC architecture shown in the diagram below. Which change would allow the private subnet to reach the internet?" — the stem explicitly references "the diagram below" and the answer depends on details (subnet layout, route tables, NAT/IGW placement) only visible in that image. Correct: `{{IMG:0}}` placed in the stem.
2. "The following EventBridge rule has a custom event pattern, as shown below. Which change would make this rule match S3 object-created events for the given bucket?" — the actual event-pattern JSON is only visible in the image; you cannot judge whether the pattern is correct without reading it. Correct: `{{IMG:0}}` placed in the stem.
3. "Based on the CloudWatch metrics graph below, showing CPUUtilization over the last hour, what Auto Scaling adjustment is most appropriate?" — the stem asks you to interpret a specific shape/value in the graph. Correct: `{{IMG:0}}` placed in the stem.
4. "A developer sees the following error in the console when deploying the Lambda function, as captured in the screenshot. What is the most likely cause?" — the exact error text/UI state is only visible in the screenshot and is the entire subject of the question. Correct: `{{IMG:0}}` placed in the stem.
- You MUST call the emit_question tool exactly once with your extraction. Do not respond with plain text.
"""


def build_system_prompt(domain_names):
    if not domain_names:
        return BASE_SYSTEM_PROMPT
    domain_list = "\n".join(f"- {d}" for d in domain_names)
    return (
        BASE_SYSTEM_PROMPT
        + "\n\nThe \"domain\" field MUST be exactly one of the following values — pick "
        "the single closest match to this question's content, or to its source "
        "category text if given. Never invent a new domain name:\n" + domain_list
    )


def build_tool_schema(domain_names):
    domain_property = {
        "type": "string",
        "description": "Exam domain/category this question belongs to.",
    }
    if domain_names:
        domain_property["enum"] = domain_names

    return {
        "toolSpec": {
            "name": "emit_question",
            "description": (
                "Emit one structured multiple-choice exam question extracted "
                "from the supplied source material — stem, alternatives, and "
                "which is correct. No explanation content — that's generated "
                "separately by the review agent."
            ),
            "inputSchema": {
                "json": {
                    "type": "object",
                    "properties": {
                        "title": {
                            "type": "string",
                            "description": "Short, descriptive title for this question.",
                        },
                        "domain": domain_property,
                        "stem": {
                            "type": "string",
                            "description": (
                                "The COMPLETE question text, copied verbatim — every scenario "
                                "paragraph plus the final question sentence, not just the last "
                                "paragraph. Never summarize or shorten it. Only include a "
                                "supplied image's {{IMG:n}} placeholder here if examining that "
                                "image is MANDATORY to answer the question (the stem explicitly "
                                "depends on it, e.g. 'as shown below')."
                            ),
                        },
                        "alternatives": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "letter": {"type": "string"},
                                    "text": {
                                        "type": "string",
                                        "description": (
                                            "The alternative's own text. Only include a supplied "
                                            "image's {{IMG:n}} placeholder here if examining that "
                                            "image is MANDATORY to answer the question — not "
                                            "merely explanatory. See the Images rule."
                                        ),
                                    },
                                    "isCorrect": {"type": "boolean"},
                                },
                                "required": ["letter", "text", "isCorrect"],
                            },
                        },
                    },
                    "required": ["title", "domain", "stem", "alternatives"],
                }
            },
        }
    }
