import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { correctLetters } from '../../core/models/question.model';
import { AiDisclaimerComponent } from '../../shared/components/ai-disclaimer.component';
import { DomainBadgeComponent } from '../../shared/components/domain-badge.component';
import { MarkdownRendererComponent } from '../review-viewer/markdown-renderer.component';
import { QuizService } from '../../core/services/quiz.service';

@Component({
  selector: 'app-quiz-runner',
  standalone: true,
  imports: [AiDisclaimerComponent, DomainBadgeComponent, MarkdownRendererComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (question(); as q) {
      <section class="runner">
        <header class="runner-header">
          <div class="progress-track"><div class="progress-fill" [style.width.%]="progressPct()"></div></div>
          <span class="progress-text">Question {{ progress().index + 1 }} of {{ progress().total }}</span>
          @if (isInstant()) {
            <span class="score-pill">Score {{ score().correct }}/{{ score().answered }}</span>
          }
        </header>

        <div class="runner-body" [class.with-palette]="!isInstant()">
          <div class="question-main">
            <div class="q-domain"><app-domain-badge [domain]="q.domain" /></div>
            <div class="q-stem"><app-markdown-renderer [source]="q.stem" /></div>
            @if (isMultiSelect()) {
              <p class="multi-hint">Select {{ requiredCount() }} answers.</p>
            }

            @for (opt of q.alternatives; track opt.letter) {
              <div
                class="option-card"
                [class.selected]="isSelected(opt.letter)"
                [class.correct]="showFeedback() && opt.isCorrect"
                [class.incorrect]="showFeedback() && isSelected(opt.letter) && !opt.isCorrect"
                [class.disabled]="answer().checked"
                (click)="onSelect(opt.letter)"
              >
                <span class="option-letter">{{ opt.letter }}</span>
                <div class="option-body">
                  <div class="option-text"><app-markdown-renderer [source]="opt.text" /></div>
                  @if (showFeedback() && opt.comment) {
                    <div class="option-comment"><app-markdown-renderer [source]="opt.comment" /></div>
                  }
                </div>
                @if (showFeedback() && opt.isCorrect) {
                  <span class="option-status">
                    <svg viewBox="0 0 24 24" width="18" height="18"><path fill="none" stroke="var(--color-green)" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" d="M5 12.5l4.5 4.5L19 7"/></svg>
                  </span>
                } @else if (showFeedback() && isSelected(opt.letter)) {
                  <span class="option-status">
                    <svg viewBox="0 0 24 24" width="18" height="18"><path fill="none" stroke="var(--color-red)" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" d="M6 6l12 12M18 6L6 18"/></svg>
                  </span>
                }
              </div>
            }

            @if (showFeedback()) {
              <app-ai-disclaimer
                [tight]="true"
                message="This content was generated by AI and may contain errors. Treat it as study support, not as an authoritative source."
              />
            }

            <div class="runner-actions">
              @if (isInstant()) {
                @if (!answer().checked) {
                  <button
                    type="button"
                    class="btn btn-ghost"
                    [disabled]="answer().selected.length === 0"
                    (click)="quiz.checkAnswer()"
                  >Check answer</button>
                } @else {
                  <button type="button" class="btn btn-primary" (click)="onNextInstant()">
                    {{ isLast() ? 'See results' : 'Next question' }}
                  </button>
                }
              } @else {
                <button type="button" class="btn btn-ghost" [disabled]="progress().index === 0" (click)="quiz.previous()">Previous</button>
                <span class="spacer"></span>
                @if (!isLast()) {
                  <button type="button" class="btn btn-ghost" (click)="quiz.next()">Next</button>
                }
                <button type="button" class="btn btn-primary" (click)="quiz.finish()">Finish exam</button>
              }
            </div>
          </div>

          @if (!isInstant()) {
            <aside class="palette">
              <h4>Questions</h4>
              <div class="palette-grid">
                @for (flag of answeredFlags(); track $index) {
                  <button
                    type="button"
                    class="palette-dot"
                    [class.answered]="flag"
                    [class.current]="$index === progress().index"
                    (click)="quiz.goTo($index)"
                  >{{ $index + 1 }}</button>
                }
              </div>
              <div class="palette-legend">
                <div class="legend-row"><span class="legend-swatch" style="background:var(--color-purple)"></span> Answered</div>
                <div class="legend-row"><span class="legend-swatch outline"></span> Unanswered</div>
                <div class="legend-row"><span class="legend-swatch current"></span> Current</div>
              </div>
            </aside>
          }
        </div>
      </section>
    }
  `,
  styles: [
    `
      :host { display: block; }
      .runner { display: flex; flex-direction: column; gap: var(--space-lg); background: var(--bg-surface); border-radius: var(--radius-lg); box-shadow: var(--shadow-sm); padding: var(--space-lg); max-width: 960px; margin: 0 auto; }
      .runner-header { display: flex; align-items: center; gap: var(--space-md); }
      .progress-track { flex: 1; height: 6px; border-radius: 999px; background: var(--bg-border); overflow: hidden; }
      .progress-fill { height: 100%; background: linear-gradient(135deg, var(--color-purple), var(--color-blue)); border-radius: 999px; }
      .progress-text { font-size: var(--font-size-xs); color: var(--text-muted); white-space: nowrap; }
      .score-pill { font-size: var(--font-size-sm); font-weight: 600; color: var(--text-secondary); background: var(--bg-elevated); padding: 4px var(--space-md); border-radius: var(--radius-pill); white-space: nowrap; }

      .runner-body { display: flex; gap: var(--space-lg); align-items: flex-start; }
      .question-main { flex: 1; min-width: 0; }

      .q-domain { margin-bottom: var(--space-sm); }
      .q-stem { font-size: var(--font-size-base); line-height: 1.55; color: var(--text-primary); margin: 0 0 var(--space-lg); }
      .multi-hint { font-size: var(--font-size-xs); color: var(--text-muted); margin: 0 0 var(--space-sm); }

      .option-card {
        display: flex; width: 100%; gap: var(--space-sm); align-items: flex-start; text-align: left;
        padding: var(--space-md); border-radius: var(--radius-md); border: 1.5px solid var(--bg-border);
        background: var(--bg-input); cursor: pointer; margin-bottom: var(--space-sm); font-family: var(--font-family);
      }
      .option-card:hover:not(.disabled) { border-color: var(--color-purple); }
      .option-card.disabled { cursor: default; }
      .option-card.selected { border-color: var(--color-purple); background: var(--bg-elevated); }
      .option-card.correct { border-color: var(--color-green); background: rgba(0, 184, 148, 0.08); }
      .option-card.incorrect { border-color: var(--color-red); background: rgba(214, 48, 49, 0.08); }
      .option-letter { width: 26px; height: 26px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: var(--font-size-sm); background: var(--bg-elevated); color: var(--text-secondary); flex-shrink: 0; }
      .option-card.selected .option-letter { background: var(--color-purple); color: #fff; }
      .option-card.correct .option-letter { background: var(--color-green); color: #fff; }
      .option-card.incorrect .option-letter { background: var(--color-red); color: #fff; }
      .option-body { flex: 1; min-width: 0; }
      .option-text { display: block; font-size: var(--font-size-base); color: var(--text-primary); line-height: 1.5; }
      .option-comment { margin: var(--space-xs) 0 0; font-size: var(--font-size-sm); color: var(--text-muted); line-height: 1.5; white-space: pre-line; }
      .option-status { flex-shrink: 0; margin-top: 3px; }

      .runner-actions { display: flex; align-items: center; gap: var(--space-sm); margin-top: var(--space-lg); }
      .spacer { flex: 1; }
      .btn { min-height: var(--touch-min); padding: 0 var(--space-lg); border-radius: var(--radius-md); font-weight: 600; font-size: var(--font-size-base); border: none; font-family: var(--font-family); cursor: pointer; }
      .btn-primary { background: linear-gradient(135deg, var(--color-purple), var(--color-blue)); color: #ffffff; }
      .btn-primary:hover { filter: brightness(1.08); }
      .btn-ghost { background: transparent; color: var(--text-secondary); border: 1px solid var(--bg-border); }
      .btn-ghost:hover:not(:disabled) { background: var(--bg-subtle); }
      .btn:disabled { opacity: 0.5; cursor: not-allowed; }

      .palette { width: 176px; flex-shrink: 0; background: var(--bg-elevated); border-radius: var(--radius-md); padding: var(--space-md); border: 1px solid var(--bg-border); }
      .palette h4 { margin: 0 0 var(--space-sm); font-size: var(--font-size-xs); color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.04em; }
      .palette-grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 6px; }
      .palette-dot { width: 28px; height: 28px; border-radius: var(--radius-sm); display: flex; align-items: center; justify-content: center; font-size: var(--font-size-xs); font-weight: 600; background: var(--bg-input); border: 1.5px solid var(--bg-border); color: var(--text-muted); cursor: pointer; font-family: var(--font-family); }
      .palette-dot.answered { background: var(--color-purple); border-color: var(--color-purple); color: #fff; }
      .palette-dot.current { box-shadow: 0 0 0 2px var(--color-blue) inset; }
      .palette-legend { margin-top: var(--space-md); display: flex; flex-direction: column; gap: 6px; font-size: var(--font-size-xs); color: var(--text-muted); }
      .legend-row { display: flex; align-items: center; gap: 6px; }
      .legend-swatch { width: 12px; height: 12px; border-radius: 3px; flex-shrink: 0; }
      .legend-swatch.outline { background: var(--bg-input); border: 1.5px solid var(--bg-border); }
      .legend-swatch.current { background: transparent; border: 2px solid var(--color-blue); }

      @media (max-width: 640px) {
        .runner-body.with-palette { flex-direction: column; }
        .palette { width: 100%; }
      }
    `,
  ],
})
export class QuizRunnerComponent {
  protected readonly quiz = inject(QuizService);

  protected readonly question = this.quiz.currentQuestion;
  protected readonly answer = this.quiz.currentAnswer;
  protected readonly progress = this.quiz.progress;
  protected readonly score = this.quiz.score;
  protected readonly answeredFlags = this.quiz.answeredFlags;
  protected readonly isMultiSelect = this.quiz.isMultiSelect;
  protected readonly requiredCount = computed(() => correctLetters(this.question() ?? { alternatives: [] }).length);

  protected readonly isInstant = computed(() => this.quiz.settings().mode === 'instant');
  protected readonly isLast = computed(() => this.progress().index === this.progress().total - 1);
  protected readonly showFeedback = computed(() => this.isInstant() && this.answer().checked);
  protected readonly progressPct = computed(() => {
    const { index, total } = this.progress();
    return total === 0 ? 0 : (index / total) * 100;
  });

  isSelected(letter: string): boolean {
    return this.answer().selected.includes(letter);
  }

  onSelect(letter: string): void {
    this.quiz.toggleOption(letter);
  }

  onNextInstant(): void {
    if (this.isLast()) {
      this.quiz.finish();
    } else {
      this.quiz.next();
    }
  }
}
